<?php include("../guest/partials/header.php");?>

<main role="main" class="container mt-5">
  <div class="jumbotron text-justify">
    <h1>AGREEMENT TO TERMS</h1>
    <p class="lead">We are Virtual-X Sdn. Bhd., doing business as Virtual-X ("Virtual-X,” “we,” “us,” or “our”), a company registered in Malaysia. 
        We operate the website through which we provide you our services, (collectively, the “Services” which include the provision and use of the Website).</p>
    <h3><u>INTELLECTUAL PROPERTY RIGHTS</u></h3>
    <p class="lead">These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and concerning your access to and use of the Website and the Services. 
        You agree that by accessing the Services, you have read, understood, and agree to be bound by all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM 
        USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
    <h3><u>Virtual-X's PRIVACY NOTICE</u></h3>
    <p class="lead">Supplemental terms and conditions or documents that may be posted on the Website from time to time are hereby expressly incorporated herein by reference. We reserve the right, in Virtual-X’s sole discretion, to make changes or modifications to these Terms of Use from time to time. 
        We will alert you about any changes by updating the “Last updated” date of these Terms of Use, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms of Use to stay informed as each time you access the Services, 
        you will be subject to, and will be deemed to have been made aware of and to have accepted, the then applicable Terms of Use.</p>
    <h3><u>INTELLECTUAL PROPERTY RIGHTS</u></h3>
    <p class="lead">Unless otherwise indicated, we retain all right, title, and interest in and to the Software and the Website, including without limitation all graphics, user interfaces, databases, functionality, software, website designs, audio, video, text, photographs, graphics, logos, and trademarks or service marks reproduced through the System. These Terms of Use do not grant you any intellectual property license or rights in or to the Software and the Website or any of its components, except to the limited extent that these Terms of Use specifically sets forth your license rights to it. You recognize that the Software and the Website and their components are protected by copyright and other laws.</p>
    <p class="lead">Conditioned upon your compliance with these Terms of Use and, if applicable, your payment of the Subscription Fees, we grant you the rights to reproduce, modify, and publicly display the Forms and use the Consent Platform (all together “Content”) on your website or mobile application. In addition, as to a Form intended to serve as a legal agreement between you and a counterparty, we grant you the right to distribute that Form to the counterparty to the extent reasonably necessary for your counterparty to execute the agreement. Under no circumstances may you use the Forms and use the Consent Platform for commercial purposes other than to facilitate compliance with applicable laws and best practices or the execution of agreements by your own business or organization. The Forms and the Consent Platform generated by the Software are licensed, not sold, and you receive no title to or ownership of the Forms or the Consent Platform.</p>
    <p class="lead">You and Virtual-X agree that none of the Feedback (as defined below) you or your users provide to us constitute confidential information, and nothing in these Terms of Use or in our dealings arising out of or related to subject matter of these Terms of Use will restrict our right to use, profit from, disclose, publish, keep secret, or otherwise exploit Feedback, without compensating or crediting you or the user in question. You hereby grant us a perpetual, irrevocable right and license to exploit the Feedback in any and every way and subject to applicable law waive any moral rights in such Feedback. Feedback will not constitute your confidential information. (“Feedback” refers to any suggestion or idea for improving or otherwise modifying any of Virtual-X’s products or services.)</p>
    <h3><u>PRIVACY NOTICE</u></h3>
    <p class="lead">We care about data privacy and security. Please review our Privacy Notice to understand our use of your personal information. You acknowledge that you have reviewed and understand our Privacy Notice.</p>
    <p class="lead">Please be advised the Services is hosted in the Malaysia. If you access the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in Malaysia, and you agree to have your data transferred to and processed in Malaysia.</p>

    <a class="btn btn-lg btn-outline-primary me-4" href="../index.php" role="button">&laquo; Back to Home </a>
    <a class="btn btn-lg btn-success" href="../general/register.php" role="button"> Sign Up Now!</a>
  </div>
</main>

<?php include("../guest/partials/footer.php") ?>